const FIELD = {
  fieldID: {
    name: '欄位ID',
    type: 'nvarchar',
    length: '50',
    allowNull: false,
    default: '',
    description: '欄位的唯一識別碼',
  },
  name: {
    name: '欄位名稱',
    type: 'nvarchar',
    length: '50',
    allowNull: false,
    default: '',
    description: '欄位的顯示名稱',
  },
  type: {
    name: '資料型別',
    type: 'nvarchar',
    length: '20',
    allowNull: false,
    default: 'nvarchar',
    description: 'SQL 資料型別 (int, nvarchar, datetime, bit, decimal 等)',
  },
  length: {
    name: '長度',
    type: 'nvarchar',
    length: '10',
    allowNull: true,
    default: '',
    description: '欄位長度或精確度設定',
  },
  allowNull: {
    name: '允許空值',
    type: 'bit',
    length: '',
    allowNull: false,
    default: 'false',
    description: '是否允許該欄位為空值',
  },
  isPrimaryKey: {
    name: '主鍵',
    type: 'bit',
    length: '',
    allowNull: false,
    default: 'false',
    description: '是否為主鍵欄位',
  },
  isIdentity: {
    name: '自動增值',
    type: 'bit',
    length: '',
    allowNull: false,
    default: 'false',
    description: '是否為自動增值欄位',
  },
  isUnique: {
    name: '唯一值',
    type: 'bit',
    length: '',
    allowNull: false,
    default: 'false',
    description: '是否為唯一值約束',
  },
  default: {
    name: '預設值',
    type: 'nvarchar',
    length: '100',
    allowNull: true,
    default: '',
    description: '欄位的預設值',
  },
  description: {
    name: '欄位描述',
    type: 'nvarchar',
    length: '255',
    allowNull: true,
    default: '',
    description: '欄位的詳細說明',
  },
  foreignKey: {
    name: '外鍵參考',
    type: 'nvarchar',
    length: '100',
    allowNull: true,
    default: '',
    description: '外鍵參考的表格.欄位 (例: Users.UserID)',
  },
  checkConstraint: {
    name: '檢查約束',
    type: 'nvarchar',
    length: '255',
    allowNull: true,
    default: '',
    description: '檢查約束條件 (例: Age >= 0)',
  },
  collation: {
    name: '定序',
    type: 'nvarchar',
    length: '50',
    allowNull: true,
    default: '',
    description: '字元定序設定',
  },
  precision: {
    name: '精確度',
    type: 'int',
    length: '',
    allowNull: true,
    default: '',
    description: 'decimal 或 numeric 型別的精確度',
  },
  scale: {
    name: '小數位數',
    type: 'int',
    length: '',
    allowNull: true,
    default: '',
    description: 'decimal 或 numeric 型別的小數位數',
  },
  isIndexed: {
    name: '建立索引',
    type: 'bit',
    length: '',
    allowNull: false,
    default: 'false',
    description: '是否在此欄位建立索引',
  },
};
